pool:
  name: Azure Pipelines
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- task: Bash@3
  displayName: 'Environment Setup'
  inputs:
    targetType: filePath
    filePath: './environment_setup/install_requirements.sh'

- task: AzureCLI@2
  displayName: 'Workspace Setup'
  inputs:
    azureSubscription: 'BMS_XRay_MLOps_SP'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'python service/code/WorkSpace.py'

- task: AzureCLI@2
  displayName: 'Azure MLOps'
  inputs:
    azureSubscription: 'BMS_XRay_MLOps_SP'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'python service/code/PipelineProcess.py'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
