# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  name: Azure Pipelines
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- task: Bash@3
  displayName: 'Environment Setup'
  inputs:
    targetType: filePath
    filePath: './environment_setup/install_requirements.sh'

- task: AzureCLI@2
  displayName: 'Workspace Setup'
  inputs:
    azureSubscription: 'BMS_XRay_MLOps_SP'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'python service/code/WorkSpace.py'

- task: AzureCLI@2
  displayName: 'Data Preprocessing'
  inputs:
    azureSubscription: 'BMS_XRay_MLOps_SP'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'python service/code/DataPreprocessing.py'

- task: AzureCLI@2
  displayName: Training
  inputs:
    azureSubscription: 'BMS_XRay_MLOps_SP'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'python service/code/Training.py'

- task: AzureCLI@2
  displayName: 'Model Registration'
  inputs:
    azureSubscription: 'BMS_XRay_MLOps_SP'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'python service/code/ModelRegistering.py'

